version: '3.8'

services:

  tandem_ai:
    image: tandem_ai:2.0
    env_file:
      - ./temp_env_files/tandem_ai.env
    depends_on:
      - chat_gpt_api
      - whisper
      - redis
    ports:
      - 4567:4567
  
  chat_gpt_api:
    image: chat_gpt_api:1.0
    env_file:
      - ./temp_env_files/chat_gpt_api.env
  
  whisper:
    image: whisper:1.0

  redis:
    image: redis:latest




