# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.1.2"

gem "puma"

gem "sinatra"
gem "sinatra-contrib"
gem 'nokogiri'
gem "erubis"
gem "redcarpet"
gem "aws-sdk-s3", "~> 1.132"
gem "mysql2"
gem "sinatra-cross_origin"
gem "down"
gem 'googleauth'
gem 'jwt'
gem "redis"