# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.1.2"
group :production do
  gem "puma"
end
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "rack-test"
gem "redcarpet"